name: 🌟 Feature request
description: Suggest a feature to improve TachiyomiJ2K
labels: [feature]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      description: What should the script do?
      placeholder: |
        Example:
          "It should work like this..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: If this is an request for a feature in [WSL2 Manager](https://github.com/bostrot/wsl2-distro-manager), I should be opening an issue in [there](https://github.com/bostrot/wsl2-distro-manager/issues)
          required: true
        - label: I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
        - label: I will fill out all of the requested information in this form.
          required: true